apiVersion: apps/v1
kind: Deployment
metadata:
  name: tang-deployment
  labels:
    app: tang
spec:
  replicas: 3
  selector:
    matchLabels:
      app: tang
  template:
    metadata:
      labels:
        app: tang
    spec:
      containers:
      - name: web
        image: howpinta/website06
        ports:
        - containerPort: 80
